### ISSUE TITLE
Can't remove New Private Window menu item in Mac

### ISSUE THREAD

**Issue by lex072** [stonecrusher/simpleMenuWizard#14]
Hello, I'm new here.
I'm using Mac OS X mavericks and recently installed FF Quantum. I think it is FF 62. I would like to remove the menu item 'New Private Window's but was unsuccessful.
I could remove the button from the hamburger menu though and also the right click context menu.
I have tried experimenting in Windows FF 62 and I could remove the menu items that I want. But in Mac OS X I couldn't.
If anyone knows please help me please. Thanks and much appreciated.

**Comment by stonecrusher** [comment]
Hi,
I think you're talking about this menu?
https://i.imgur.com/rUfsrbs.png

So you could partly remove stuff in MacOS or didn't it work at all in MacOS?
Unfortunately I don't have a Mac system here to test, so we have to run through it step by step with your help.

First it would be helpful if you can post your userChrome.css here.

**Comment by stonecrusher** [comment]
I also retested before and can confirm it works with different versions of Windows and Linux MINT.
I have absolutely no experience with Macs and no possibility to test :-/

> For some reasons which I don't know the Mac OS X menu items can't be edited by your CSS.

Same here. I can only imagine it to be a rights conflict. I don't think that FF has different CSS selectors for Mac menus.

Aris overall is more competent than me with FF CSS and I also thought that JS might be a solution. However I would recommend trying method 2 first, because sooner or later (or already?) method 1 will not work anymore.

Sorry I can't really help here.

**Comment by lex072** [comment]
No problem pal. All is good. I was using FF 52 for a while and also the menu wizard add-on. For some reason which wasn't necessary I accidentally updated FF to 62. So that's why. Everything doesn't work. However I feel that your codes are rocking good. Just that apple makes everything so b** complicated. 
I can't seem to find any info on how FF targets or reference the menu items in Mac OS X.
No worries though. Your codes are working great in Windows.
I'm in the process of trying Aris methods and will keep you updated.
Cheers!!

**Comment by lex072** [comment]
Method 1 works already. I'm trying out method 2.
