### ISSUE TITLE
Howto disable/remove blank context menu — include ff actions?

### ISSUE THREAD

**Issue by tmpm697** [stonecrusher/simpleMenuWizard#43]
I can wipe out all components in blank context menu and whenever I right click in an empty space, it'll create a dot (ff tries to create/open the context) and must left click to dismiss it to use other functions like scroll page. 

How to completely remove blank context menu for even exist?

I tried to seach context and bank in ff config but don't find any options to disable it.

**Comment by stonecrusher** [comment]
I don't think it's possible because it doesn't know that it's blank and the internal very big context menu doesn't differentiate.

You might just wipe out every context menu by
`#mainPopupSet { display: none !important; }`
if that is what you want.
If that doesn't work either, it's not possible with CSS and you need JS modifications.

**Comment by tmpm697** [comment]
I had the line but still the dot, so JavaScript needed.
