### ISSUE TITLE
Kudos!

### ISSUE THREAD

**Issue by Skrell** [stonecrusher/simpleMenuWizard#64]
Just wanted to say how much I love this simple mod to Firefox!!

**Comment by stonecrusher** [comment]
Thank you, that makes me happy!

Of course it could be a bit easier and best might be to make an addon from it, but due to technical security limitations that's not possible. Fortunately, people who consider modding the browser themselves by using instructions from a github repo are tech-savvy enough to perceive the instructions as "simple".
