### ISSUE TITLE
zoom menu item in main hamburger doesn't work

### ISSUE THREAD

**Issue by wordpure** [stonecrusher/simpleMenuWizard#67]
After uncommenting some of the comments in the image below in main hamburger, the menu items such as printing are hidden normally, but the zoom menu item is still displayed.

![图片](https://user-images.githubusercontent.com/68013962/183364072-6b0cad16-c107-4f86-89d0-0491112f84a3.png)

![图片](https://user-images.githubusercontent.com/68013962/183364923-547a5e05-d97b-40a3-94e1-9bf0ae02d420.png)

**Comment by stonecrusher** [comment]
Strange. I just tested it with FF 103.0.1 and it works as it should.
I'm sure you already restarted the browser. And `toolkit.legacyUserProfileCustomizations.stylesheets` is already *true*, otherwise it wouldn't have removed the other items.

The code you screenshotted looks good to me.

Can you test it with a fresh profile? Just go to `about:profiles` and make a new one. You need to install SMW there again.

**Comment by wordpure** [comment]
Sorry, I forgot to include my Firefox version when I reported.

I applied your suggestion in Firefox 104.0b6 (the version used at the time of reporting) and 103.0.
103.0 works fine, but 104.0b6 still fails to hide the zoom menu item.

Perhaps this is a change brought about by a browser update?

**Comment by stonecrusher** [comment]
Yes then there will probably be a change of identifiers.
This project only targets current release versions, not beta / nightly. But I'll leave this open in preparation for the change.

**Comment by stonecrusher** [comment]
hint:
New ID is simply `#appMenu-zoom-controls` without the `2`
Same goes for the toolbarseparator below

**Comment by wordpure** [comment]
After changing to the new id, the zoom menu item can also be hidden.

Thanks for your patient reply.
