### ISSUE TITLE
Does nothing on Nightly?

### ISSUE THREAD

**Issue by firefoxlover** [stonecrusher/simpleMenuWizard#89]
I am using (selfbuilt) Firefox nightly but it uses my old profile (I can verify it uses it from the "last used" date of some files.)

I have `toolkit.legacyUserProfileCustomizations.stylesheets` = true in about:config.

`userChrome.css` and the folder with the different settings is in the profile folder, I changed some in the tab settings. Restarted firefox but it doesnt do anything? This is really strange.

An idea could be that you need to enable those customizations when building firefox?

I am on Fedora 39 KDE

**Comment by stonecrusher** [comment]
I'm sorry, I have no idea why it doesn't work. It's not tested under Nightly.

I don't think you need to change something with the build process.

There might be changes so that not everything works in the newer FF versions. As a test, try to remove lots of different context menu items so you are sure it works/doesn't work at all.

Also make sure the files are where they belong. `userChrome.css` shouldn't be in the profile folder, it should be in `profileFolder/chrome/`

**Comment by firefoxlover** [comment]
sorry, I totally forgot this one.
